[package]
name = "level2-balance-query"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "balance"
path = "src/balance.rs"

[dependencies]

ethers = "2.0"
tokio = { version = "1", features = ["full"] }